import fs from 'fs';
import path from 'path';

// ---------------------------------------------------------------------------
// GA4 RAW ROW SHAPE
// ---------------------------------------------------------------------------
interface GA4Row {
    'Event name': string;
    'Button Name'?: string;
    'Event count': number;
    'Session source'?: string;
    'Session medium'?: string;
    'Country'?: string;
    [key: string]: any;
}

// ---------------------------------------------------------------------------
// FILTER RULES — extend these lists as needed without touching logic
// ---------------------------------------------------------------------------

// Sessions originating from localhost, staging, or internal IP ranges
const DEV_SOURCE_PATTERNS: RegExp[] = [
    /localhost/i,
    /127\.0\.0\.1/,
    /192\.168\./,
    /staging/i,
    /internal/i,
];

// Known bot/crawler user agent session sources GA4 sometimes leaks through
const BOT_SOURCE_PATTERNS: RegExp[] = [
    /bot/i,
    /spider/i,
    /crawl/i,
    /lighthouse/i,
    /gtmetrix/i,
    /pingdom/i,
];

// Button names generated by admin/dev tooling — not real donor intent
const ADMIN_BUTTON_PATTERNS: RegExp[] = [
    /test/i,
    /debug/i,
    /admin/i,
    /preview/i,
];

// ---------------------------------------------------------------------------
// HELPERS — DRY pattern matchers
// ---------------------------------------------------------------------------
const matchesAny = (value: string | undefined, patterns: RegExp[]): boolean =>
    !!value && patterns.some(p => p.test(value));

const isDevRow = (row: GA4Row): boolean => matchesAny(row['Session source'], DEV_SOURCE_PATTERNS);
const isBotRow = (row: GA4Row): boolean => matchesAny(row['Session source'], BOT_SOURCE_PATTERNS);
const isAdminClick = (row: GA4Row): boolean => matchesAny(row['Button Name'], ADMIN_BUTTON_PATTERNS);

// ---------------------------------------------------------------------------
// MAIN EXPORT
// ---------------------------------------------------------------------------

/**
 * Reads analytics_output.json, strips developer/bot/admin noise,
 * and returns only legitimate user-intent rows.
 * Returns [] if the file doesn't exist yet — same safe behaviour as before.
 */
export function loadCleanGA4Data(): GA4Row[] {
    const filePath = path.resolve(process.cwd(), 'analytics_output.json');

    if (!fs.existsSync(filePath)) {
        return [];
    }

    try {
        const raw: GA4Row[] = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

        const before = raw.length;
        const clean = raw.filter(row => !isDevRow(row) && !isBotRow(row) && !isAdminClick(row));
        const dropped = before - clean.length;

        if (dropped > 0) {
            console.log(`GA4 Sanitizer: Dropped ${dropped}/${before} noisy rows.`);
        }

        return clean;
    } catch (error) {
        console.error('⚠️ GA4 Sanitizer: Failed to parse analytics_output.json', error);
        return [];
    }
}

/**
 * Returns the top-performing button name from clean GA4 data,
 * or null if no qualifying clicks exist.
 */
export function getTopButtonAction(): string | null {
    const data = loadCleanGA4Data();

    const buttonClicks = data.filter(row =>
        row['Event name'] === 'core_button_link_click' &&
        row['Button Name'] &&
        row['Button Name'] !== '(not set)'
    );

    if (buttonClicks.length === 0) return null;

    const top = buttonClicks.sort((a, b) => b['Event count'] - a['Event count'])[0];
    return top?.['Button Name'] ?? null;
}