import pandas as pd

def load_ga4_export(filepath):
    """
    Safely loads a GA4 CSV export, bypassing Google's metadata rows.
    """
    try:
        # 'comment=#' skips the top metadata lines generated by GA4
        df = pd.read_csv(filepath, comment='#')
        # Standardize column names (strip trailing spaces GA4 sometimes adds)
        df.columns = df.columns.str.strip()
        return df
    except FileNotFoundError:
        print(f"Error: Could not find the file at {filepath}")
        return pd.DataFrame()

def extract_core_button_metrics(df):
    """
    Isolates custom button tracking and calculates engagement depth.
    """
    # 1. Filter out everything except our custom event
    btn_df = df[df['Event name'] == 'core_button_link_click'].copy()
    
    if btn_df.empty:
        print("No 'core_button_link_click' events found in this dataset.")
        return btn_df

    # 2. Check if the user remembered to export the 'button_name' secondary dimension
    if 'Button Name' in btn_df.columns:
        print("--- Custom Button Performance Breakdown ---")
        # Sort by most clicked buttons
        breakdown = btn_df[['Button Name', 'Event count', 'Total users', 'Event count per active user']]
        print(breakdown.sort_values(by='Event count', ascending=False).to_string(index=False))
    elif 'button_name' in btn_df.columns: # Fallback just in case
        print("--- Custom Button Performance Breakdown ---")
        breakdown = btn_df[['button_name', 'Event count', 'Total users', 'Event count per active user']]
        print(breakdown.sort_values(by='Event count', ascending=False).to_string(index=False))
    else:
        print("--- High-Level Button Performance (No parameters exported) ---")
        summary = btn_df[['Event name', 'Event count', 'Total users', 'Event count per active user']]
        print(summary.to_string(index=False))
        print("\n*Tip: Add 'button_name' as a secondary dimension in GA4 before your next export for deeper insights!*")
        
    return btn_df

def analyze_overall_traffic(df):
    """
    Provides a quick health-check on overall site traffic from the Events report.
    """
    print("\n--- Overall Site Traffic Health ---")
    
    # Extract baseline page views
    page_views = df[df['Event name'] == 'page_view']['Event count'].sum()
    total_users = df[df['Event name'] == 'page_view']['Total users'].sum()
    
    if total_users > 0:
        views_per_user = page_views / total_users
        print(f"Total Page Views: {page_views}")
        print(f"Total Unique Users: {total_users}")
        print(f"Average Pages per User: {views_per_user:.2f}")

# ==========================================
# Execution Workflow
# ==========================================
if __name__ == "__main__":
    filepath = 'Events_Event_name.csv'
    
    print(f"Loading GA4 data from: {filepath}...\n")
    ga4_data = load_ga4_export(filepath)
    
    if not ga4_data.empty:
        # Run our specific analytics models
        extract_core_button_metrics(ga4_data)
        analyze_overall_traffic(ga4_data)
        ga4_data.to_json('../analytics_output.json', orient='records')
